### ISSUE TITLE
sound loop when enemy drops weapon too close to walls (ex. doomforever-redux)

### ISSUE THREAD

**Issue by ryan-sg** [3dfxdev/hyper3DGE#28]
As I originally tried to report in https://github.com/3dfxdev/hyper3DGE/issues/27, though completely incorrect hypothesis, I have discovered the exact cause!

Map02 works good because there are corridors with lots of enemies that are likely to die near a wall, when they drop their weapon (shotguys, former humans both) and it lands really close to a wall, the sprite is clipped into the wall a bit.  When this happens, the drop sound repeats endlessly.

I isolated one enemy and shot him and got the sound started.  Once the sound looped, I dispersed enough ammunition to be able to pick up the dropped rifle close to the wall.   Once picked up, the sound stopped!  Hooray!

I have a save file attached, hopefully it works for you to be able to load the problem.  It should load with the sound playing, shoot off a shotgun round so you can pick it up and the sound should stop.

[slot023.zip](https://github.com/3dfxdev/hyper3DGE/files/477972/slot023.zip)
need to run 3dge with the doomforever-redux mod as its a good example with enemies dropping guns with extra sounds and stuff.

**Comment by Corbachu** [comment]
It's been a crazy week for us -- finally back at it, will check this out tonight!! =D

**Comment by Corbachu** [comment]
We have fixed this in the latest Git revision - please try this out again, and if it comes up then we will inspect it. If not, I will close and mark as fixed! =) 

Specifically tested with Duke it out in DOOM.

**Comment by ryan-sg** [comment]
hmm, i was able to quickly reproduce the problem still with doom4ever-redux, still on map02, right after I shot the shotguy behind the red key bars  his shotty landed too close to the wall and clickityclickityclickity....etc

i'm at revision 4fac0fb9f04f589d405b5437c59148c0522be3c6, plus my 'merge' to my local branch, plus my bsd-makefile-fix commit.

**Comment by Corbachu** [comment]
Issue 1: Yes, the pitch shift table needs slight improvements =D

Issue 2: This was recently fixed in commit 0e564ba, so please check that and make sure it is indeed fixed. 

I'm going to close this now -- if you feel like it should be re-opened (since none of us can replicate the issue now), let me know and I'll re-open it.

**Comment by ryan-sg** [comment]
I hope commenting on this doesn't auto-reopen it, but just for clarification do you mean that you guys also tried doomforever-redux (doom4ever-redux?) and can't reproduce the issue there whereas I still can?  Before I say much more i'm pulling the latest changes anyway and I'll double check again.  Cheers!

**Comment by ryan-sg** [comment]
:(  I was able to reproduce the issue again in DukeOut just now, bahh

**Comment by Corbachu** [comment]
How are you doing it? Having videos showing this behavior would help immensely at this point, because me nor Chilly experience the issue. If you can record it, I can try better to isolate it! ^_^

**Comment by ryan-sg** [comment]
Just re-verified in the last built binary where I thought it was gone and it was still there too, I guess I just was really flukey to not bring it out.  In my haste to see the fixed barrel placements (they ARE fixed!) i just turned on noclip to see them real quick, enemies shooting at me hit each other and started it.

So easy way is, -warp 02, then idclip, iddqd, idkfa, rocket launcher out, blow up EVERYTHING and you'll have a lot of it hehe.

**Comment by ryan-sg** [comment]
I tried to record a video of this issue with my phone in a hurry, mmsing to myself was probably a bad idea as you can barely see ANYTHING.  (sideways because i had to use a kleenex box as a phone holder so I could play LOL)

Buut, we want sound, and you can still hear it.  You can hear my noisy mechanical keyboard, but right at the end when I've stopped at the red keycard the sound has started and I can hear it through this dinky terrible video :D

http://ryan.slipgate.org/3dge_soundloop.mp4

**Comment by Corbachu** [comment]
The only thing I can think of at this point are these few commits, which updated the core math functions awhile back by Brendan and another user -- this broken behavior seemed to happen shortly after these were made. Chilly, if you can, look over these and make sure they aren't wrong. .

e8ea9b8

2e07d3a

a4f8a73

901ca31

103dc3a

bdc2d23

**Comment by Corbachu** [comment]
Also, ryan-sg, it might be wise to replay this with Interpolation off (r_lerp 0 and r_vsync 0) to make sure it's not the interpolation code mucking things up...?

**Comment by ryan-sg** [comment]
Just checked out r_lerp 0; r_vsync 0 here and it still happens, so it seems interpolation code is not to blame.

I don't have time right now, but I can take a stab at reverting those commits you posted above one at a time to see if they help.  (Actually, might try at first by reverting ALL, then adding them back one by one...)

**Comment by Corbachu** [comment]
Also, Ryan,what is your full name so I can properly add you to AUTHORS?

**Comment by ryan-sg** [comment]
Ryan Freeman, cheers!

**Comment by ryan-sg** [comment]
sorry guys, i haven't had a chance to look into this just yet, been so busy trying to get another car purchased i haven't even had a moment on the computer for long.  I haven't forgot about it!

**Comment by Corbachu** [comment]
@ryan-sg  is this still happening? I can't get it to bug out like this for the life of me >.<
